name: jeevansetu
description: SIH 2026 PS26001 AI landslide monitoring and disaster response prototype.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/hero_mountain.jpg
    - assets/images/monitoring_mountain.jpg
    - assets/images/rescue_diver.jpg
