name: jeevansetu
description: SIH 2026 PS26001 AI landslide monitoring and disaster response prototype.
publish_to: 'none'
version: 3.0.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/reference_atlas.b64
    - assets/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
