import 'dart:async';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

void main() => runApp(const JeevanSetuApp());

const navy = Color(0xFF063B4C);
const cyan = Color(0xFF20C5D8);
const blue = Color(0xFF3D83F7);
const red = Color(0xFFFF4057);
const green = Color(0xFF28C98B);
const orange = Color(0xFFFFA638);
const bg = Color(0xFFF3F8FA);

class JeevanSetuApp extends StatelessWidget {
  const JeevanSetuApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'JeevanSetu',
      theme: ThemeData(
        useMaterial3: true,
        scaffoldBackgroundColor: bg,
        colorScheme: ColorScheme.fromSeed(seedColor: cyan, primary: cyan, secondary: blue, surface: Colors.white),
        fontFamily: 'Roboto',
        appBarTheme: const AppBarTheme(backgroundColor: bg, surfaceTintColor: bg, elevation: 0),
      ),
      home: const SplashScreen(),
    );
  }
}

Route<T> appRoute<T>(Widget page) => PageRouteBuilder<T>(
  transitionDuration: const Duration(milliseconds: 420),
  reverseTransitionDuration: const Duration(milliseconds: 320),
  pageBuilder: (_, a, __) => FadeTransition(opacity: a, child: page),
  transitionsBuilder: (_, a, __, child) => SlideTransition(
    position: Tween(begin: const Offset(.035, .018), end: Offset.zero).animate(CurvedAnimation(parent: a, curve: Curves.easeOutCubic)),
    child: child,
  ),
);

class LogoMark extends StatelessWidget {
  final double size;
  final Color color;
  const LogoMark({super.key, this.size = 68, this.color = Colors.white});
  @override
  Widget build(BuildContext context) => SizedBox(width: size, height: size * .72, child: CustomPaint(painter: LogoPainter(color)));
}

class LogoPainter extends CustomPainter {
  final Color color;
  LogoPainter(this.color);
  @override
  void paint(Canvas c, Size s) {
    final p = Paint()..color = color..style = PaintingStyle.stroke..strokeWidth = s.width * .115..strokeCap = StrokeCap.square..strokeJoin = StrokeJoin.miter;
    final path = Path()..moveTo(s.width*.08,s.height*.86)..lineTo(s.width*.43,s.height*.18)..lineTo(s.width*.69,s.height*.63)..lineTo(s.width*.91,s.height*.39);
    c.drawPath(path,p);
    c.drawLine(Offset(s.width*.37,s.height*.64),Offset(s.width*.69,s.height*.64),Paint()..color=color.withOpacity(.72)..strokeWidth=s.width*.07..strokeCap=StrokeCap.round);
  }
  @override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false;
}

class MountainScene extends StatefulWidget {
  final Widget child;
  final bool dark;
  const MountainScene({super.key, required this.child, this.dark = true});
  @override State<MountainScene> createState()=>_MountainSceneState();
}

class _MountainSceneState extends State<MountainScene> with SingleTickerProviderStateMixin {
  late final AnimationController c;
  @override void initState(){super.initState();c=AnimationController(vsync:this,duration:const Duration(seconds:9))..repeat();}
  @override void dispose(){c.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>AnimatedBuilder(animation:c,builder:(_,__)=>Stack(fit:StackFit.expand,children:[
    DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:widget.dark?const [Color(0xFF0A5871),Color(0xFF052F3E),Color(0xFF021D27)]:const [Color(0xFFDBF7FB),Color(0xFF8ADDE8),Color(0xFF469EB8)]))),
    Positioned(top:-70+math.sin(c.value*math.pi*2)*9,left:-80,right:-80,height:260,child:CustomPaint(painter:CloudPainter(c.value))),
    Positioned(left:-15,right:-15,bottom:0,height:430,child:CustomPaint(painter:MountainPainter(c.value,dark:widget.dark))),
    Positioned.fill(child:DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.transparent,Colors.transparent,Colors.black.withOpacity(widget.dark?.26:.08)])))),
    widget.child,
  ]));
}

class CloudPainter extends CustomPainter {
  final double t; CloudPainter(this.t);
  @override void paint(Canvas c,Size s){final p=Paint()..color=Colors.white.withOpacity(.06);for(int i=0;i<8;i++){final x=(i*137+t*s.width*.16)%s.width;final y=30+(i%3)*52.0;c.drawOval(Rect.fromCenter(center:Offset(x,y),width:150+(i%2)*80,height:38),p);}}
  @override bool shouldRepaint(covariant CustomPainter old)=>true;
}
class MountainPainter extends CustomPainter {
  final double t; final bool dark; MountainPainter(this.t,{required this.dark});
  @override void paint(Canvas c,Size s){
    final back=Paint()..color=(dark?const Color(0xFF174E57):const Color(0xFF3E8E8D)).withOpacity(.82);
    final mid=Paint()..color=dark?const Color(0xFF0C3C43):const Color(0xFF287272);
    final front=Paint()..color=dark?const Color(0xFF062B32):const Color(0xFF164D53);
    Path p1=Path()..moveTo(0,s.height)..lineTo(0,s.height*.55)..lineTo(s.width*.18,s.height*.27)..lineTo(s.width*.34,s.height*.57)..lineTo(s.width*.54,s.height*.18)..lineTo(s.width*.74,s.height*.55)..lineTo(s.width*.88,s.height*.31)..lineTo(s.width,s.height*.6)..lineTo(s.width,s.height)..close(); c.drawPath(p1,back);
    Path p2=Path()..moveTo(0,s.height)..lineTo(0,s.height*.72)..lineTo(s.width*.22,s.height*.46)..lineTo(s.width*.42,s.height*.68)..lineTo(s.width*.63,s.height*.36)..lineTo(s.width*.79,s.height*.67)..lineTo(s.width,s.height*.48)..lineTo(s.width,s.height)..close(); c.drawPath(p2,mid);
    Path p3=Path()..moveTo(0,s.height)..lineTo(0,s.height*.83)..lineTo(s.width*.17,s.height*.69)..lineTo(s.width*.35,s.height*.82)..lineTo(s.width*.58,s.height*.62)..lineTo(s.width*.77,s.height*.81)..lineTo(s.width,s.height*.7)..lineTo(s.width,s.height)..close(); c.drawPath(p3,front);
  }
  @override bool shouldRepaint(covariant CustomPainter old)=>true;
}

class SplashScreen extends StatefulWidget { const SplashScreen({super.key}); @override State<SplashScreen> createState()=>_SplashScreenState(); }
class _SplashScreenState extends State<SplashScreen> with SingleTickerProviderStateMixin {
  late final AnimationController c;
  @override void initState(){super.initState();c=AnimationController(vsync:this,duration:const Duration(milliseconds:1800))..repeat();Timer(const Duration(milliseconds:2300),(){if(mounted)Navigator.pushReplacement(context,appRoute(const OnboardingScreen()));});}
  @override void dispose(){c.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(body:MountainScene(child:SafeArea(child:Padding(padding:const EdgeInsets.all(28),child:Column(children:[
    const Spacer(),const LogoMark(size:92),const SizedBox(height:12),const Text('JeevanSetu',style:TextStyle(color:Colors.white,fontSize:34,fontWeight:FontWeight.w900)),const Text('AI Disaster Monitoring & Response',style:TextStyle(color:Colors.white70,fontSize:13)),
    const Spacer(),AnimatedBuilder(animation:c,builder:(_,__)=>Column(children:[const Text('Preparing live risk intelligence',style:TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:10),ClipRRect(borderRadius:BorderRadius.circular(9),child:LinearProgressIndicator(value:c.value,minHeight:5,backgroundColor:Colors.white24,valueColor:const AlwaysStoppedAnimation(Colors.white)))])),
  ])))));
}

class OnboardingScreen extends StatefulWidget { const OnboardingScreen({super.key}); @override State<OnboardingScreen> createState()=>_OnboardingScreenState(); }
class _OnboardingScreenState extends State<OnboardingScreen>{
  final PageController pc=PageController(); int index=0;
  final pages=const [
    ('Safer communities with smarter monitoring','AI-assisted landslide risk intelligence combines rainfall, terrain and field signals into one clear safety view.',Icons.radar_rounded),
    ('Real-time risk map for Nepal','Explore actual map tiles, risk hotspots, shelters and road conditions instead of a static screenshot.',Icons.public_rounded),
    ('Report · Respond · Stay Safe','Citizens, rescue teams, authorities, volunteers and organisations work through one coordinated experience.',Icons.health_and_safety_rounded),
  ];
  @override Widget build(BuildContext context)=>Scaffold(body:PageView.builder(controller:pc,itemCount:3,onPageChanged:(v)=>setState(()=>index=v),itemBuilder:(_,i){final p=pages[i];return MountainScene(child:SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(26,28,26,26),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    const Spacer(),Container(width:78,height:78,decoration:BoxDecoration(color:Colors.white.withOpacity(.13),borderRadius:BorderRadius.circular(24),border:Border.all(color:Colors.white24)),child:Icon(p.$3,color:Colors.white,size:38)),const SizedBox(height:24),Text(p.$1,style:const TextStyle(color:Colors.white,fontSize:29,fontWeight:FontWeight.w900,height:1.05)),const SizedBox(height:14),Text(p.$2,style:const TextStyle(color:Colors.white70,fontSize:14,height:1.45)),const SizedBox(height:34),
    Row(children:[...List.generate(3,(n)=>AnimatedContainer(duration:const Duration(milliseconds:250),margin:const EdgeInsets.only(right:7),height:6,width:n==i?28:7,decoration:BoxDecoration(color:n==i?cyan:Colors.white30,borderRadius:BorderRadius.circular(9)))),const Spacer(),TextButton(onPressed:()=>Navigator.push(context,appRoute(const RoleSelectScreen())),child:const Text('Skip',style:TextStyle(color:Colors.white70))),const SizedBox(width:6),FloatingActionButton.small(heroTag:'ob$i',backgroundColor:cyan,elevation:0,onPressed:(){if(i<2){pc.nextPage(duration:const Duration(milliseconds:420),curve:Curves.easeOutCubic);}else{Navigator.push(context,appRoute(const RoleSelectScreen()));}},child:Icon(i==2?Icons.check_rounded:Icons.arrow_forward_rounded,color:navy))])
  ])))));});
}

enum UserRole { citizen, rescue, authority, volunteer, organization }
extension RoleX on UserRole { String get title=>switch(this){UserRole.citizen=>'Citizen',UserRole.rescue=>'Rescue Team',UserRole.authority=>'Authority',UserRole.volunteer=>'Volunteer',UserRole.organization=>'Organization'}; IconData get icon=>switch(this){UserRole.citizen=>Icons.person_rounded,UserRole.rescue=>Icons.health_and_safety_rounded,UserRole.authority=>Icons.account_balance_rounded,UserRole.volunteer=>Icons.volunteer_activism_rounded,UserRole.organization=>Icons.business_center_rounded}; Color get color=>switch(this){UserRole.citizen=>green,UserRole.rescue=>red,UserRole.authority=>blue,UserRole.volunteer=>const Color(0xFF7C5CE1),UserRole.organization=>orange}; String get subtitle=>switch(this){UserRole.citizen=>'Receive alerts, report incidents and stay safe',UserRole.rescue=>'Coordinate missions and respond faster',UserRole.authority=>'Monitor risk, verify alerts and manage response',UserRole.volunteer=>'Help communities and support relief operations',UserRole.organization=>'Offer shelters, resources and logistics support'}; }

class RoleSelectScreen extends StatelessWidget { const RoleSelectScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(body:MountainScene(child:SafeArea(child:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
  IconButton(onPressed:()=>Navigator.maybePop(context),icon:const Icon(Icons.arrow_back_rounded,color:Colors.white)),const SizedBox(height:8),const Text('Choose your role',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('The home experience adapts to the work you need to do.',style:TextStyle(color:Colors.white70)),const SizedBox(height:22),
  ...UserRole.values.map((r)=>Padding(padding:const EdgeInsets.only(bottom:11),child:InkWell(borderRadius:BorderRadius.circular(18),onTap:()=>Navigator.push(context,appRoute(LoginScreen(role:r))),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:r.color.withOpacity(.92),borderRadius:BorderRadius.circular(18),boxShadow:[BoxShadow(color:r.color.withOpacity(.22),blurRadius:16,offset:const Offset(0,7))]),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:Colors.white.withOpacity(.9),borderRadius:BorderRadius.circular(14)),child:Icon(r.icon,color:r.color)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(r.title,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:2),Text(r.subtitle,style:const TextStyle(color:Colors.white70,fontSize:11))])),const Icon(Icons.chevron_right_rounded,color:Colors.white)]))))
])))));
}

class LoginScreen extends StatelessWidget { final UserRole role; const LoginScreen({super.key,required this.role}); @override Widget build(BuildContext context)=>Scaffold(body:MountainScene(child:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
  IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded,color:Colors.white)),const SizedBox(height:20),Center(child:Column(children:[LogoMark(size:72,color:role.color),const SizedBox(height:8),const Text('JeevanSetu',style:TextStyle(color:Colors.white,fontSize:23,fontWeight:FontWeight.w900))])),const SizedBox(height:28),Text('${role.title} sign in',style:const TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(role.subtitle,style:const TextStyle(color:Colors.white60,fontSize:12)),const SizedBox(height:22),
  const FrostField(icon:Icons.person_outline_rounded,hint:'Email or phone'),const SizedBox(height:11),const FrostField(icon:Icons.lock_outline_rounded,hint:'Password',obscure:true),const SizedBox(height:20),SizedBox(width:double.infinity,height:52,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:role.color,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),onPressed:()=>Navigator.pushAndRemoveUntil(context,appRoute(AppShell(role:role)),(_)=>false),child:Text('Continue as ${role.title}',style:const TextStyle(fontWeight:FontWeight.w900)))),const SizedBox(height:12),Center(child:TextButton(onPressed:()=>Navigator.pushAndRemoveUntil(context,appRoute(AppShell(role:role)),(_)=>false),child:const Text('Use demo access',style:TextStyle(color:Colors.white70))))
])))))); }
class FrostField extends StatelessWidget { final IconData icon;final String hint;final bool obscure;const FrostField({super.key,required this.icon,required this.hint,this.obscure=false});@override Widget build(BuildContext context)=>TextField(obscureText:obscure,style:const TextStyle(color:Colors.white),decoration:InputDecoration(prefixIcon:Icon(icon,color:Colors.white70),hintText:hint,hintStyle:const TextStyle(color:Colors.white54),filled:true,fillColor:Colors.white.withOpacity(.10),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:const BorderSide(color:Colors.white24)),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:const BorderSide(color:cyan)))));}

class AppShell extends StatefulWidget { final UserRole role; const AppShell({super.key,required this.role}); @override State<AppShell> createState()=>_AppShellState(); }
class _AppShellState extends State<AppShell>{int index=0;@override Widget build(BuildContext context){final pages=[HomeScreen(role:widget.role),const LiveMapScreen(),const SosScreen(),const AlertsScreen(),MoreScreen(role:widget.role)];return Scaffold(body:IndexedStack(index:index,children:pages),bottomNavigationBar:NavigationBar(height:70,selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),backgroundColor:Colors.white,indicatorColor:const Color(0xFFD9F5F8),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home_rounded),label:'Home'),NavigationDestination(icon:Icon(Icons.map_outlined),selectedIcon:Icon(Icons.map_rounded),label:'Map'),NavigationDestination(icon:Icon(Icons.sos_outlined),selectedIcon:Icon(Icons.sos_rounded),label:'SOS'),NavigationDestination(icon:Icon(Icons.notifications_none_rounded),selectedIcon:Icon(Icons.notifications_rounded),label:'Alerts'),NavigationDestination(icon:Icon(Icons.menu_rounded),label:'More')]));}}

class HomeScreen extends StatelessWidget { final UserRole role; const HomeScreen({super.key,required this.role}); @override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:EdgeInsets.zero,children:[
  SizedBox(height:255,child:MountainScene(child:Padding(padding:const EdgeInsets.fromLTRB(18,16,18,18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[CircleAvatar(backgroundColor:role.color,child:Icon(role.icon,color:Colors.white)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Namaste,',style:TextStyle(color:Colors.white60,fontSize:11)),Text(role.title,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:16))])),Container(width:40,height:40,decoration:BoxDecoration(color:Colors.white12,borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.notifications_active_rounded,color:Colors.white))]),const Spacer(),const Text('Nepal Risk Intelligence',style:TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:4),const Text('Know the slope before it moves.',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900,height:1.0)),const SizedBox(height:12),Row(children:[_heroStat('HIGH','Risk','78%',red),const SizedBox(width:8),_heroStat('24H','Rainfall','126 mm',blue),const SizedBox(width:8),_heroStat('LIVE','Shelters','18',green)])])))),
  Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    InkWell(borderRadius:BorderRadius.circular(18),onTap:()=>Navigator.push(context,appRoute(const EarlyWarningScreen())),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFF334E),Color(0xFFE75B69)]),borderRadius:BorderRadius.circular(18),boxShadow:[BoxShadow(color:red.withOpacity(.18),blurRadius:18,offset:const Offset(0,8))]),child:const Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.warning_amber_rounded,color:Colors.white,size:28),SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('High landslide risk',style:TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900)),SizedBox(height:3),Text('Sindhupalchok corridor · next 12 hours',style:TextStyle(color:Colors.white70,fontSize:12)),SizedBox(height:11),Text('Open early warning  →',style:TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w800))]))]))),
    const SizedBox(height:18),const Text('Live situation',style:TextStyle(fontWeight:FontWeight.w900,fontSize:17)),const SizedBox(height:10),Row(children:[Expanded(child:_action(context,Icons.radar_rounded,'Risk map','Live hotspots',blue,const LiveMapScreen())),const SizedBox(width:10),Expanded(child:_action(context,Icons.route_rounded,'Safe route','Avoid closures',green,const SafeRouteScreen()))]),const SizedBox(height:10),Row(children:[Expanded(child:_action(context,Icons.add_a_photo_outlined,'Report','AI assisted',orange,const ReportScreen())),const SizedBox(width:10),Expanded(child:_action(context,Icons.inventory_2_outlined,'Relief','18 nearby',const Color(0xFF7C5CE1),const ResourcesScreen()))]),
    const SizedBox(height:18),const Text('AI insight',style:TextStyle(fontWeight:FontWeight.w900,fontSize:17)),const SizedBox(height:10),_glassCard(child:InkWell(onTap:()=>Navigator.push(context,appRoute(const AiAnalysisScreen())),child:const Row(children:[CircleAvatar(backgroundColor:Color(0xFFE8F4FF),child:Icon(Icons.auto_awesome_rounded,color:blue)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Why is risk increasing?',style:TextStyle(fontWeight:FontWeight.w900)),SizedBox(height:3),Text('Rainfall saturation + steep terrain + historical failures',style:TextStyle(color:Colors.black54,fontSize:11))])),Icon(Icons.chevron_right_rounded)]))),
    if(role!=UserRole.citizen)...[const SizedBox(height:18),Text('${role.title} command tools',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17)),const SizedBox(height:10),_roleTools(context,role)],
  ]))
]));
Widget _heroStat(String a,String b,String v,Color c)=>Expanded(child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:9),decoration:BoxDecoration(color:Colors.white.withOpacity(.10),borderRadius:BorderRadius.circular(14),border:Border.all(color:Colors.white12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:TextStyle(color:c,fontSize:9,fontWeight:FontWeight.w900)),Text(v,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),Text(b,style:const TextStyle(color:Colors.white60,fontSize:9))])));
Widget _action(BuildContext c,IconData i,String t,String s,Color col,Widget p)=>InkWell(onTap:()=>Navigator.push(c,appRoute(p)),borderRadius:BorderRadius.circular(18),child:_glassCard(child:Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:col.withOpacity(.12),borderRadius:BorderRadius.circular(14)),child:Icon(i,color:col)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900)),Text(s,style:const TextStyle(color:Colors.black45,fontSize:10))]))])));
Widget _roleTools(BuildContext c,UserRole r)=>_glassCard(child:Column(children:[if(r==UserRole.rescue)...[_toolRow(Icons.crisis_alert_rounded,'Mission queue','3 active rescue calls',red),_toolRow(Icons.route_rounded,'Fastest response route','ETA 18 min',green)]else if(r==UserRole.authority)...[_toolRow(Icons.verified_user_outlined,'Verify community alerts','7 awaiting review',blue),_toolRow(Icons.campaign_outlined,'Broadcast warning','Target risk polygons',red)]else if(r==UserRole.volunteer)...[_toolRow(Icons.volunteer_activism_outlined,'Volunteer missions','4 nearby tasks',green),_toolRow(Icons.inventory_outlined,'Supply delivery','2 priority camps',orange)]else ...[_toolRow(Icons.home_work_outlined,'Shelter capacity','68% available',green),_toolRow(Icons.inventory_2_outlined,'Resource inventory','Medical kits low',orange)]]));
Widget _toolRow(IconData i,String t,String s,Color c)=>ListTile(contentPadding:EdgeInsets.zero,leading:Icon(i,color:c),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:13)),subtitle:Text(s,style:const TextStyle(fontSize:10)),trailing:const Icon(Icons.chevron_right_rounded));}

Widget _glassCard({required Widget child})=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),boxShadow:[BoxShadow(color:navy.withOpacity(.05),blurRadius:18,offset:const Offset(0,7))]),child:child);

class LiveMapScreen extends StatefulWidget { const LiveMapScreen({super.key}); @override State<LiveMapScreen> createState()=>_LiveMapScreenState(); }
class _LiveMapScreenState extends State<LiveMapScreen> with SingleTickerProviderStateMixin {
  final MapController map=MapController(); late final AnimationController pulse; bool satelliteRisk=true;
  final hotspots=const [
    (LatLng(27.9506,85.6846),red,'Sindhupalchok','Critical · 86%'),
    (LatLng(27.7172,85.3240),orange,'Kathmandu','High · 64%'),
    (LatLng(28.2096,83.9856),orange,'Pokhara','High · 58%'),
    (LatLng(27.5330,84.3542),green,'Chitwan','Low · 24%'),
  ];
  @override void initState(){super.initState();pulse=AnimationController(vsync:this,duration:const Duration(milliseconds:1200))..repeat(reverse:true);}
  @override void dispose(){pulse.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,12,16,10),child:Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Live Risk Map',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text('OpenStreetMap · Nepal risk layer',style:TextStyle(fontSize:10,color:Colors.black45))])),IconButton(onPressed:()=>map.move(const LatLng(27.85,85.4),7.4),icon:const Icon(Icons.my_location_rounded))])),Expanded(child:Stack(children:[
    FlutterMap(mapController:map,options:const MapOptions(initialCenter:LatLng(27.85,85.4),initialZoom:7.4,minZoom:5,maxZoom:18),children:[
      TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.sih.jeevansetu'),
      PolygonLayer(polygons:[Polygon(points:const [LatLng(27.78,85.44),LatLng(28.02,85.54),LatLng(28.11,85.84),LatLng(27.86,85.93),LatLng(27.70,85.67)],color:red.withOpacity(.18),borderColor:red.withOpacity(.75),borderStrokeWidth:2),Polygon(points:const [LatLng(28.05,83.78),LatLng(28.32,83.89),LatLng(28.23,84.16),LatLng(27.99,84.12)],color:orange.withOpacity(.14),borderColor:orange.withOpacity(.7),borderStrokeWidth:2)]),
      MarkerLayer(markers:hotspots.map((h)=>Marker(point:h.$1,width:68,height:68,child:GestureDetector(onTap:()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(h.$3,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(h.$4,style:TextStyle(color:h.$2,fontWeight:FontWeight.w800)),const SizedBox(height:12),const Text('AI factors: intense rainfall, soil saturation and terrain susceptibility.'),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('Acknowledge')))]))),child:AnimatedBuilder(animation:pulse,builder:(_,__)=>Stack(alignment:Alignment.center,children:[Container(width:50+pulse.value*12,height:50+pulse.value*12,decoration:BoxDecoration(shape:BoxShape.circle,color:h.$2.withOpacity(.14))),Icon(Icons.location_on_rounded,color:h.$2,size:40)]))))).toList()),
    ]),
    Positioned(top:12,left:12,right:12,child:Row(children:[_mapChip('Live AI layer',Icons.radar_rounded,red),const SizedBox(width:7),_mapChip('4 hotspots',Icons.warning_amber_rounded,orange)])),
    Positioned(bottom:12,left:12,child:Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:5),decoration:BoxDecoration(color:Colors.white.withOpacity(.9),borderRadius:BorderRadius.circular(8)),child:const Text('© OpenStreetMap contributors',style:TextStyle(fontSize:9)))),
    Positioned(right:12,bottom:16,child:Column(children:[FloatingActionButton.small(heroTag:'z1',backgroundColor:Colors.white,onPressed:()=>map.move(map.camera.center,map.camera.zoom+1),child:const Icon(Icons.add,color:navy)),const SizedBox(height:8),FloatingActionButton.small(heroTag:'z2',backgroundColor:Colors.white,onPressed:()=>map.move(map.camera.center,map.camera.zoom-1),child:const Icon(Icons.remove,color:navy)),const SizedBox(height:8),FloatingActionButton.small(heroTag:'route',backgroundColor:cyan,onPressed:()=>Navigator.push(context,appRoute(const SafeRouteScreen())),child:const Icon(Icons.route_rounded,color:navy))]))
  ]))]));
  Widget _mapChip(String t,IconData i,Color c)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:8),decoration:BoxDecoration(color:Colors.white.withOpacity(.94),borderRadius:BorderRadius.circular(12),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.06),blurRadius:10)]),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(i,color:c,size:16),const SizedBox(width:5),Text(t,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:10))]));
}

class AiAnalysisScreen extends StatelessWidget { const AiAnalysisScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('AI Risk Analysis',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(16),children:[
  _glassCard(child:const Row(children:[Icon(Icons.location_on_outlined),SizedBox(width:8),Text('Sindhupalchok, Nepal',style:TextStyle(fontWeight:FontWeight.w800))])),const SizedBox(height:12),_glassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Landslide probability',style:TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:18),Center(child:Stack(alignment:Alignment.center,children:[const SizedBox(width:138,height:138,child:CircularProgressIndicator(value:.78,strokeWidth:12,backgroundColor:Color(0xFFFFE4E8),valueColor:AlwaysStoppedAnimation(red))),Column(children:[const Text('78%',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),Text('HIGH RISK',style:TextStyle(color:red,fontWeight:FontWeight.w900,fontSize:10))])])),const SizedBox(height:20),_factor(Icons.water_drop_outlined,'Rainfall intensity','126 mm / 24h',blue),_factor(Icons.landscape_outlined,'Soil saturation','High',green),_factor(Icons.change_history_rounded,'Terrain slope','37°',orange),_factor(Icons.history_rounded,'Historical failures','Frequent',red)])),const SizedBox(height:12),_glassCard(child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(Icons.auto_awesome_rounded,color:blue),SizedBox(width:8),Text('AI explanation',style:TextStyle(fontWeight:FontWeight.w900))]),SizedBox(height:8),Text('Risk increased because prolonged rainfall has saturated steep slopes in a historically failure-prone corridor. The prototype surfaces both the score and the reasons so responders can act on evidence.',style:TextStyle(height:1.45,color:Colors.black87))]))
])); }
Widget _factor(IconData i,String a,String b,Color c)=>Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Row(children:[Icon(i,color:c,size:19),const SizedBox(width:9),Expanded(child:Text(a,style:const TextStyle(fontSize:12))),Text(b,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:12))]));

class EarlyWarningScreen extends StatelessWidget { const EarlyWarningScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Early Warning',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[red,Color(0xFFE23B58)]),borderRadius:BorderRadius.circular(18)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(Icons.warning_amber_rounded,color:Colors.white,size:28),SizedBox(width:8),Text('High Risk Alert',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900))]),SizedBox(height:10),Text('Potential landslide activity within the next 12 hours.',style:TextStyle(color:Colors.white,fontSize:15,height:1.4)),SizedBox(height:8),Text('Sindhupalchok risk corridor',style:TextStyle(color:Colors.white70,fontSize:11))])),const SizedBox(height:14),_warning(Icons.route_rounded,orange,'Avoid vulnerable roads','Use the recommended safe corridor and avoid steep cut slopes.'),_warning(Icons.home_work_outlined,green,'Nearest shelter ready','Community shelter has available capacity and basic medical support.'),_warning(Icons.share_location_rounded,blue,'Share your status','Family and response teams can see your last safety check-in.'),const SizedBox(height:12),FilledButton(style:FilledButton.styleFrom(backgroundColor:red,padding:const EdgeInsets.all(15)),onPressed:()=>Navigator.push(context,appRoute(const LiveMapScreen())),child:const Text('View affected zone on map',style:TextStyle(fontWeight:FontWeight.w900))),const SizedBox(height:8),OutlinedButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Alert prepared for sharing'))),child:const Text('Share alert'))])); }
Widget _warning(IconData i,Color c,String t,String s)=>Padding(padding:const EdgeInsets.only(bottom:10),child:_glassCard(child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:c),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(s,style:const TextStyle(fontSize:11,color:Colors.black54,height:1.35))]))])));

class SafeRouteScreen extends StatelessWidget { const SafeRouteScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Safe Route',style:TextStyle(fontWeight:FontWeight.w900))),body:Stack(children:[FlutterMap(options:const MapOptions(initialCenter:LatLng(27.78,85.55),initialZoom:9),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.sih.jeevansetu'),PolygonLayer(polygons:[Polygon(points:const [LatLng(27.77,85.49),LatLng(27.86,85.56),LatLng(27.82,85.72),LatLng(27.73,85.66)],color:red.withOpacity(.16),borderColor:red,borderStrokeWidth:2)]),PolylineLayer(polylines:[Polyline(points:const [LatLng(27.72,85.32),LatLng(27.76,85.40),LatLng(27.80,85.46),LatLng(27.84,85.42),LatLng(27.89,85.50)],color:cyan,strokeWidth:6)]),MarkerLayer(markers:const [Marker(point:LatLng(27.72,85.32),width:44,height:44,child:Icon(Icons.location_on_rounded,color:blue,size:40)),Marker(point:LatLng(27.89,85.50),width:44,height:44,child:Icon(Icons.home_work_rounded,color:green,size:38))])]),Positioned(top:12,left:12,right:12,child:_glassCard(child:const Column(children:[Row(children:[Icon(Icons.my_location_rounded,size:18),SizedBox(width:8),Expanded(child:Text('Kathmandu · Current position',style:TextStyle(fontWeight:FontWeight.w800,fontSize:12)))]),Divider(),Row(children:[Icon(Icons.shield_outlined,size:18),SizedBox(width:8),Expanded(child:Text('Safe Shelter North · recommended',style:TextStyle(fontWeight:FontWeight.w800,fontSize:12)))])]))),Positioned(left:12,right:12,bottom:16,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:cyan,foregroundColor:navy,padding:const EdgeInsets.all(16)),onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Navigation started: avoiding active high-risk polygon'))),child:const Text('Start safe navigation · 28 min',style:TextStyle(fontWeight:FontWeight.w900))))])); }

class SosScreen extends StatefulWidget { const SosScreen({super.key}); @override State<SosScreen> createState()=>_SosScreenState(); }
class _SosScreenState extends State<SosScreen> with SingleTickerProviderStateMixin { late final AnimationController c; @override void initState(){super.initState();c=AnimationController(vsync:this,duration:const Duration(milliseconds:1150))..repeat(reverse:true);}@override void dispose(){c.dispose();super.dispose();}@override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Center(child:Text('SOS Emergency',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900))),const SizedBox(height:30),Center(child:GestureDetector(onLongPress:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('SOS request sent to the nearest response unit'))),child:AnimatedBuilder(animation:c,builder:(_,__)=>Container(width:176+c.value*16,height:176+c.value*16,decoration:BoxDecoration(shape:BoxShape.circle,color:red.withOpacity(.12),boxShadow:[BoxShadow(color:red.withOpacity(.2),blurRadius:34,spreadRadius:8)]),alignment:Alignment.center,child:Container(width:132,height:132,decoration:const BoxDecoration(shape:BoxShape.circle,color:red),alignment:Alignment.center,child:const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('SOS',style:TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900)),Text('PRESS & HOLD',style:TextStyle(color:Colors.white70,fontSize:9,fontWeight:FontWeight.w800))]))))),const SizedBox(height:20),const Center(child:Text('Shares your selected incident details and approximate demo location with the response workflow.',textAlign:TextAlign.center,style:TextStyle(color:Colors.black54,fontSize:11))),const SizedBox(height:18),_glassCard(child:Column(children:[_option(Icons.crisis_alert_rounded,'Emergency type','Landslide'),_option(Icons.groups_outlined,'People affected','3 people'),_option(Icons.medical_services_outlined,'Medical support','Required'),_option(Icons.photo_camera_outlined,'Evidence','Add photo / video')]))])); }
Widget _option(IconData i,String t,String s)=>ListTile(contentPadding:EdgeInsets.zero,leading:Icon(i,color:navy),title:Text(t,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800)),subtitle:Text(s,style:const TextStyle(fontSize:10)),trailing:const Icon(Icons.chevron_right_rounded));

class ReportScreen extends StatefulWidget { const ReportScreen({super.key}); @override State<ReportScreen> createState()=>_ReportScreenState(); }
class _ReportScreenState extends State<ReportScreen>{String type='Landslide';bool submitted=false;@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Report Incident',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(16),children:[Container(height:180,decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),gradient:const LinearGradient(colors:[Color(0xFF5F7566),Color(0xFF273D34)])),child:Stack(children:[Positioned.fill(child:CustomPaint(painter:ReportArtPainter())),const Positioned(left:14,bottom:14,child:Text('Tap to add field photo / video',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800,fontSize:11))])),const SizedBox(height:12),_glassCard(child:const Row(children:[Icon(Icons.location_on_outlined),SizedBox(width:8),Expanded(child:Text('Auto location · Sindhupalchok, Nepal',style:TextStyle(fontWeight:FontWeight.w800,fontSize:12)))])),const SizedBox(height:14),const Text('Incident type',style:TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:8),Wrap(spacing:7,runSpacing:7,children:['Landslide','Flood','Road Block','Bridge Damage'].map((e)=>ChoiceChip(label:Text(e),selected:type==e,onSelected:(_)=>setState(()=>type=e))).toList()),const SizedBox(height:12),TextField(maxLines:3,decoration:InputDecoration(hintText:'Describe what you can see...',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(15),borderSide:BorderSide.none))),const SizedBox(height:12),FilledButton(style:FilledButton.styleFrom(backgroundColor:cyan,foregroundColor:navy,padding:const EdgeInsets.all(15)),onPressed:(){setState(()=>submitted=true);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Report submitted for AI triage and authority review')));},child:Text(submitted?'Report submitted ✓':'Submit report',style:const TextStyle(fontWeight:FontWeight.w900))) ]));}
}
class ReportArtPainter extends CustomPainter { @override void paint(Canvas c,Size s){final p=Paint()..color=const Color(0xFF879B76);final path=Path()..moveTo(0,s.height)..lineTo(0,s.height*.45)..lineTo(s.width*.25,s.height*.2)..lineTo(s.width*.48,s.height*.53)..lineTo(s.width*.68,s.height*.25)..lineTo(s.width,s.height*.58)..lineTo(s.width,s.height)..close();c.drawPath(path,p);final debris=Paint()..color=const Color(0xFF8A674E);c.drawOval(Rect.fromLTWH(s.width*.2,s.height*.55,s.width*.6,s.height*.32),debris);} @override bool shouldRepaint(covariant CustomPainter old)=>false; }

class ResourcesScreen extends StatelessWidget { const ResourcesScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Relief & Resources',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(16),children:[_resource(Icons.home_work_rounded,'Barhabise Community Shelter','2.1 km · 68% capacity',green),_resource(Icons.local_hospital_outlined,'District Emergency Clinic','4.6 km · 24×7 support',red),_resource(Icons.water_drop_outlined,'Water Distribution Point','1.8 km · stock available',blue),_resource(Icons.inventory_2_outlined,'Relief Supply Hub','5.4 km · food + blankets',orange)])); }
Widget _resource(IconData i,String t,String s,Color c)=>Padding(padding:const EdgeInsets.only(bottom:10),child:_glassCard(child:Row(children:[CircleAvatar(backgroundColor:c.withOpacity(.12),child:Icon(i,color:c)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900)),Text(s,style:const TextStyle(fontSize:10,color:Colors.black54))])),const Icon(Icons.chevron_right_rounded)])));

class AlertsScreen extends StatelessWidget { const AlertsScreen({super.key}); @override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('Alerts',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:14),_alert(Icons.warning_amber_rounded,red,'High landslide risk','Sindhupalchok · active now'),_alert(Icons.cloudy_snowing,blue,'Heavy rainfall forecast','Next 6 hours · mountain districts'),_alert(Icons.block_rounded,orange,'Road closure reported','Araniko Highway · community verified'),_alert(Icons.home_work_outlined,green,'Shelter capacity updated','Barhabise shelter · space available')])); }
Widget _alert(IconData i,Color c,String t,String s)=>Padding(padding:const EdgeInsets.only(bottom:10),child:_glassCard(child:Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:c.withOpacity(.12),borderRadius:BorderRadius.circular(14)),child:Icon(i,color:c)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900)),Text(s,style:const TextStyle(fontSize:10,color:Colors.black54))])),const Icon(Icons.chevron_right_rounded)])));

class MoreScreen extends StatelessWidget { final UserRole role; const MoreScreen({super.key,required this.role}); @override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('More',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:14),_glassCard(child:Row(children:[CircleAvatar(backgroundColor:role.color,child:Icon(role.icon,color:Colors.white)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${role.title} demo',style:const TextStyle(fontWeight:FontWeight.w900)),const Text('SIH 2026 · PS26001',style:TextStyle(fontSize:10,color:Colors.black54))]))])),const SizedBox(height:12),_more(context,Icons.smart_toy_outlined,'AI Safety Assistant',const AssistantScreen()),_more(context,Icons.family_restroom_rounded,'Family Safety',const FamilyScreen()),_more(context,Icons.inventory_2_outlined,'Relief Resources',const ResourcesScreen()),_more(context,Icons.map_outlined,'Offline-ready map concept',const LiveMapScreen()),_more(context,Icons.switch_account_outlined,'Switch profession',const RoleSelectScreen(),replace:true),_more(context,Icons.info_outline_rounded,'About JeevanSetu',const AboutScreen())])); }
Widget _more(BuildContext c,IconData i,String t,Widget p,{bool replace=false})=>Padding(padding:const EdgeInsets.only(bottom:8),child:_glassCard(child:ListTile(contentPadding:EdgeInsets.zero,leading:Icon(i,color:navy),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:13)),trailing:const Icon(Icons.chevron_right_rounded),onTap:()=>replace?Navigator.pushAndRemoveUntil(c,appRoute(p),(_)=>false):Navigator.push(c,appRoute(p)))));

class AssistantScreen extends StatefulWidget { const AssistantScreen({super.key}); @override State<AssistantScreen> createState()=>_AssistantScreenState(); }
class _AssistantScreenState extends State<AssistantScreen>{final input=TextEditingController();final List<String> messages=[];@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('AI Safety Assistant',style:TextStyle(fontWeight:FontWeight.w900))),body:Column(children:[Expanded(child:ListView(padding:const EdgeInsets.all(16),children:[const Icon(Icons.smart_toy_rounded,color:blue,size:64),const Center(child:Text('Ask JeevanSetu',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900))),const SizedBox(height:16),...['Why is my area high risk?','Show the nearest safe shelter','Which road should I avoid?','What should my family do now?'].map((e)=>Padding(padding:const EdgeInsets.only(bottom:8),child:_glassCard(child:ListTile(contentPadding:EdgeInsets.zero,dense:true,leading:const Icon(Icons.auto_awesome_rounded,color:blue,size:18),title:Text(e,style:const TextStyle(fontSize:12)),onTap:()=>setState(()=>messages.add(e))))),...messages.map((m)=>Align(alignment:Alignment.centerRight,child:Container(margin:const EdgeInsets.only(top:8),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:const Color(0xFFDFF6FA),borderRadius:BorderRadius.circular(14)),child:Text(m,style:const TextStyle(fontSize:12))))])),SafeArea(top:false,child:Padding(padding:const EdgeInsets.all(12),child:TextField(controller:input,decoration:InputDecoration(hintText:'Ask about risk, routes or safety...',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none),suffixIcon:IconButton(icon:const Icon(Icons.send_rounded,color:cyan),onPressed:(){if(input.text.trim().isNotEmpty){setState(()=>messages.add(input.text.trim()));input.clear();}})))))]));}
}
class FamilyScreen extends StatelessWidget { const FamilyScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Family Safety',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(16),children:[_family('You','Safe · live check-in',green),_family('Mother','Safe · 2 min ago',green),_family('Father','Last seen · 42 min ago',orange),_family('Sister','Check-in requested',red),const SizedBox(height:10),FilledButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Safety check-in sent'))),child:const Text('Send family safety check-in'))])); }
Widget _family(String t,String s,Color c)=>Padding(padding:const EdgeInsets.only(bottom:8),child:_glassCard(child:Row(children:[CircleAvatar(backgroundColor:c.withOpacity(.12),child:Icon(Icons.person_rounded,color:c)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900)),Text(s,style:TextStyle(fontSize:10,color:c))])),const Icon(Icons.chevron_right_rounded)])));

class AboutScreen extends StatelessWidget { const AboutScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('About',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(20),children:[const SizedBox(height:18),const Center(child:LogoMark(size:90,color:cyan)),const SizedBox(height:8),const Center(child:Text('JeevanSetu',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900,color:navy))),const Center(child:Text('SIH 2026 · PS26001',style:TextStyle(color:Colors.black45))),const SizedBox(height:22),_glassCard(child:const Text('A professional Flutter prototype for AI-assisted landslide monitoring, transparent risk explanation, early warning, safe routing, citizen reporting and multi-agency disaster response in Nepal.',style:TextStyle(height:1.5))),const SizedBox(height:10),_glassCard(child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Judge-visible differentiators',style:TextStyle(fontWeight:FontWeight.w900)),SizedBox(height:8),Text('• Interactive OpenStreetMap risk layer\n• Animated hotspot and SOS states\n• Role-aware citizen/rescue/authority/volunteer/NGO entry\n• Explainable AI risk factors\n• Safe-route hazard avoidance\n• Community incident workflow\n• Relief-resource discovery\n• Family safety + AI assistant')]))])); }
